content_dir:
  "./website"
  # base_url:
  # "https://pubgo-test.surge.sh"
base_url: ""
port: 8889
site:
  # image paths are relative to content_dir
  name: "PUBGO"
  favicon: "/static/icon.png"
  stylesheet: "/static/css/custom.css"
  title: Dynamic Content Publishing Framework in Go
  footer_content: "PUBGO est. 2023"
  logo: "/static/icon-no-back.png"
  logo_width: "1.4em"
  logo_height: "1.4em"
  logo_text: "PUBGO"
  pages:
    0:
      name: "home"
      path: "/"
      hide_from_nav: true
      collection: false
      hero:
        image: "/static/logo.svg"
        background_image: "/static/inspiration-geometry.png"
    1:
      name: "docs"
      path: "/docs"
      collection: false
    4:
      name: "posts"
      path: "/posts"
      collection: true
      hero:
        content: "Readings"
        background_image: "/static/inspiration-geometry.png"
    5:
      name: "news"
      path: "/news"
      collection: true
      hero:
        content: "News"
        background_image: "/static/inspiration-geometry.png"
  theme:
    syntax_highlight: true
    # see https://github.com/alecthomas/chroma/tree/master/styles for a list of
    # styles
    syntax_theme: "onedark"
    bg: "#eeeeee"
    fg: "#020202"
    muted_accent: "#515e15"
    accent: "#4d1406"
    secondary_font: "-apple-system, BlinkMacSystemFont, Roboto, Oxygen, Ubuntu, Cantarell, sans-serif"
