content_dir:
  "./website"
  # base_url:
  # "https://pubgo-test.surge.sh"
base_url: ""
port: 8889
site:
  # image paths are relative to content_dir
  name: "PubGo"
  favicon: "/static/icon.png"
  stylesheet: "/static/css/custom.css"
  title: Dynamic Content Publishing Framework in Go
  footer_content: "PubGo © 2023"
  logo: "/static/icon-no-back.png"
  logo_text: "pubgo"
  pages:
    0:
      name: "home"
      path: "/"
      hide_from_nav: true
      collection: false
      hero:
        image: "/static/logo.svg"
        background_image: "/static/inspiration-geometry.png"
        background: "#eeeeee"
    1:
      name: "docs"
      path: "/docs"
      collection: false
    4:
      name: "posts"
      path: "/posts"
      collection: true
      hero:
        content: "Readings"
        background_image: "/static/inspiration-geometry.png"
        background: "#4d1406"
    5:
      name: "news"
      path: "/news"
      collection: true
      hero:
        content: "News"
        background_image: "/static/inspiration-geometry.png"
        background: "#515e15"
  theme:
    syntax_highlight: true
    background_color: "#eeeeee"
    text_color: "#020202"
    main_color: "#515e15"
    accent_color: "#4d1406"
    font_family: "-apple-system, BlinkMacSystemFont, Roboto, Oxygen, Ubuntu, Cantarell, sans-serif"
